spring.application.name=PSPBackend

spring.docker.compose.enabled=false

spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/psp
spring.datasource.username=postgres
spring.datasource.password=super

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
