spring.application.name=PSPBackend

spring.docker.compose.enabled=false

spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/psp
spring.datasource.username=postgres
spring.datasource.password=super

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

psp.shared-secret=${PSP_SHARED_SECRET}

server.port=8445
server.ssl.key-store=${KEYSTORE:src/main/resources/psp.p12}
server.ssl.key-store-password=${KEYSTORE_PASSWORD:JakaSifr@1}
server.ssl.key-alias=${KEYSTORE_ALIAS:psp_backend}