apiVersion: v1
kind: Service
metadata:
  name: psp-mysql-service  # Ovo će biti "hostname" za tvoj Spring Boot
spec:
  ports:
    - port: 3306
  selector:
    app: psp-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psp-mysql-deployment
spec:
  selector:
    matchLabels:
      app: psp-mysql
  template:
    metadata:
      labels:
        app: psp-mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"  # Stavi šifru koju inače koristiš u Springu
        - name: MYSQL_DATABASE
          value: "psp_db" # Ime tvoje baze
        ports:
        - containerPort: 3306
          name: mysql