spring.application.name=BankBackend

server.port=8443
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:bank_be.p12
server.ssl.key-store-password=JakaSifr@1
server.ssl.key-alias=bank_backend

spring.ssl.bundle.jks.mytrust.truststore.location=classpath:truststore.p12
spring.ssl.bundle.jks.mytrust.truststore.type=PKCS12
spring.ssl.bundle.jks.mytrust.truststore.password=JakaSifr@1

spring.datasource.driverClassName=org.postgresql.Driver
spring.sql.init.mode=always
#spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/bank-sep
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.docker.compose.enabled=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.show_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.flyway.enabled=false

psp.shared-secret=${PSP_SHARED_SECRET}
spring.docker.compose.enabled=false