spring.application.name=WebShopBackend

#server.port=8070
server.port=8444
server.ssl.key-store=${KEYSTORE:src/main/resources/web_shop_backend.p12}
server.ssl.key-store-password=${KEYSTORE_PASSWORD:JakaSifr@1}
server.ssl.key-alias=${KEYSTORE_ALIAS:web_shop_backend}

#server.ssl.enabled=false

spring.datasource.driverClassName=org.postgresql.Driver
spring.sql.init.mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/web-shop-sep
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.show_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.flyway.enabled=false

psp.merchant_id =1
psp.merchant_password=$2a$12$vMJga57Pqt4ZwktqirCGF.MUaVR0Fi4l8EUlSOqu05zUylEwlPTrm
psp.url=https://localhost:8445/payment/merchant-request

spring.ssl.bundle.jks.mytrust.truststore.location=classpath:truststore.p12
spring.ssl.bundle.jks.mytrust.truststore.type=PKCS12
spring.ssl.bundle.jks.mytrust.truststore.password=JakaSifr@1
